# Generated by Django 5.0.1 on 2024-05-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_details', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('vendor_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('on_time_delivery_rate', models.FloatField(null=True)),
                ('quality_rating_avg', models.FloatField(null=True)),
                ('average_response_time', models.FloatField(null=True)),
                ('fulfillment_rate', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'VendorModel',
                'verbose_name_plural': 'VendorModels',
            },
        ),
    ]
